actor.js, client.js, util.js
Small modifications required for sidechain transfer.
=> Modifications for sidechain transfer

src/client.ts, src/contract.ts, src/evm-contract.ts, src/tests/evm_test.ts
This is a repush of https://github.com/loomnetwork/loom-js/pull/12
=> Split Contract. New EvmContract object. Transaction hash.

src/client.ts, src/index.ts, src/internal/ws-rpc-client.ts, src/tests/e2e/ws-rpc-client-tests.ts, src/tests/e2e_tests.ts, src/tests/helpers.ts, src/types/rpcwebsockets.d.ts
=> Emit connection events and errors from client

src/client.ts, src/loom-provider.ts, src/proto/loom.proto, src/proto/loom_pb.d.ts
- Supporting necessary events to work with Truffle
- Supporting deploy of contracts on DappChain
- Handle more events on WebSocket
- Remove listeners on the client after disconnect
- Adding account (still simple) handle support
=> Loom provider truffle events support

src/loom-provider.ts
* Although the answer is just empty, in order to satisfy request
=> Answering request from logs call

src/client.ts, src/contract.ts, src/evm-contract.ts, src/loom-provider.ts
And query is now broken... oddly enough.
=> Add optional query caller

src/plasma-cash/entity.ts, src/plasma-cash/ethereum-client.ts
- Adds bindings for `challengeBefore`
- Adds bindings for `respondChallengeBefore`
=> Challenge Before Bindings

src/index.ts, src/plasma-cash/entity.ts, src/plasma-cash/ethereum-client.ts
Adds challengingTxHash parameter for responding to challenges, which allows picking a challenge based on its transaction's hash.
=> Add challengingTxHash parameter

src/plasma-cash/contracts/plasma-cash-abi.json
Updates saved Plasma Cash ABI to match changes in https://github.com/loomnetwork/plasma-erc721/pull/106
=> Update Plasma Cash ABI

src/plasma-cash/contracts/plasma-cash-abi.json
=> Update Plasma Cash ABI for ETH - ERC20 Suport

src/loom-provider.ts
change _netVersion to return client.chainId
=> Return chain id 

.gitignore, e2e_tests.sh, package.json, src/tests/e2e/coin-tests.ts
* Updated .gitignore
* Update test local for macOS support
* Test allowance on Coin updated
=> Updates on build and test

package.json, src/plasma-cash/contracts/plasma-cash-abi.json, src/plasma-cash/entity.ts, src/plasma-cash/ethereum-client.ts, src/plasma-cash/plasma-cash-block.ts, yarn.lock
Implements:
- updated function bindings for RootChain.sol
- automatic challenging for challenge{Before,Between,After} as in https://github.com/loomnetwork/plasma-cash/blob/master/plasma_cash/client/client.py#L347
- retrieval of a coin's history.
=> Plasma Cash automatic challenges via `WatchExit`

e2e_tests.sh, package.json, src/index.ts, src/plasma-cash/cached-dappchain-client.ts, src/plasma-cash/db.ts, src/plasma-cash/entity.ts, src/plasma-cash/ethereum-client.ts, src/plasma-cash/plasma-cash-tx.ts, src/plasma-cash/signed-contract.ts, src/solidity-helpers.ts, src/tests/e2e/address-mapper-tests.ts, webpack.config.js, yarn.lock
Implements:
- **Offline signing of transactions**: Removes the limitation of having our keys on the connecting node. This is a necessary step for users wanting to connect and interact with the deployed contracts via infura. 
- **Caching middleware**: Fetch data regarding the coins owned by a user from a local json "database" if they have them already, otherwise poll the node and save locally.
- Minor bug fixes regarding BNs & formatting
- Stateful client API
=> Plasma Cash UX Improvements - Offline Signing

src/plasma-cash/entity.ts, src/plasma-cash/user.ts
Deposit/token related functions should be part of the application
=> Remove redundant params

src/plasma-cash/db.ts, src/plasma-cash/entity.ts, src/plasma-cash/user.ts, src/tests/unit/plasma-cash/database-tests.ts, src/tests/unit/plasma-cash/entity-tests.ts
- Users can stop watching by supplying coin slot
- Receive coin to user class
- Improve block history retrieval algo for edge cases.
=> Minor UX Upgrade on Watching

e2e_support/genesis.json, src/contracts/transfer-gateway.ts, src/loom-provider.ts, src/tests/e2e/contract-tests.ts, src/tests/e2e/dpos-tests.ts, src/tests/e2e/evm-contract-tests.ts, src/tests/e2e/loom-provider-web3-tests.ts, src/tests/e2e_tests.ts
* Fix loom provider receipt return (the root cause to get test stuck)
=> Fixing and organize tests

src/plasma-cash/plasma-cash-tx.ts
Closes https://github.com/loomnetwork/loom-js/issues/66
=> Fix type mismatch

src/plasma-cash/entity.ts, src/plasma-cash/ethereum-client.ts, src/plasma-cash/user.ts
* Force slot and blockNumber toString
* Converting addresses to checkSum addresses or Metamask will fail
* getCoinFromTxAsync using index 0 (length == 1)
* getting event deposit correctly
=> Small fixes after testing

package.json, src/tests/e2e/loom-provider-web3-tests.ts, yarn.lock
Rollback to avoid https://github.com/ethereum/web3.js/issues/1916 and https://github.com/ethereum/web3.js/issues/1559#issuecomment-412348642
=> Downgrade to web3-beta.33

.gitignore, .travis_e2e_test.sh, e2e_plasma_cash_test.sh, e2e_tests.sh
* Adding plasma-cash test
* Honest test 
* Hostile test
=> Adding plasma-cash test

src/plasma-cash/user.ts
* Removed unused variables
* Fix ABI for allowance, adding view keyword
* Translate Ethers.js BigNumber to BN
* Fix amount issue on ABI adding toString
* Fix tx return from depositERC20 contract
=> Fixed on depositERC20 function

.travis_e2e_test.sh, src/contracts/dpos2.ts, src/proto/dposv2.proto, src/proto/dposv2_pb.d.ts
Match https://github.com/loomnetwork/go-loom/commit/8da2a53bd81b2a74edd83098193c6b8e7089b901
=> Use updated list-validators proto

src/client.ts, src/index.ts, src/loom-provider.ts, src/tests/e2e/client-test-tx-cache.ts, src/tests/e2e_tests.ts
* Returning error on Tx already exists in cache
=> Retry disabled by default

src/tests/e2e/loom-provider-web3-child-events.ts, src/tests/e2e/loom-provider-web3-subevents.ts, src/tests/e2e_tests.ts
* Created a test to check if events emitted on child contracts can be
catched using the event system
=> Test child contract catch event

README.md, src/loom-provider.ts, src/tests/e2e/loom-provider-tests.ts
* Adding more flexible eth methods, now is possible to add methods that
aren't provided also to overwrite default methods
=> Loom provider flexible Eth methods

src/client.ts
Increase minimum polling interval to 3s.
=> Tweak default polling strategy for TxSyncBroadcaster

.travis_e2e_test.sh, src/loom-provider.ts, src/proto/evm.proto, src/proto/evm_pb.d.ts, src/tests/e2e/evm-contract-tests.ts, src/tests/e2e/loom-provider-tests.ts, src/tests/e2e/loom-provider-web3-tests.ts
* Also adding blockHash and transactionIndex to receipt
* Adding blockTime to logs from eth_getLogs
=> Add block time to EVM events

src/address.ts, src/contracts/address-mapper.ts, src/contracts/dpos.ts, src/contracts/dpos2.ts, src/contracts/transfer-gateway.ts, src/plasma-cash/plasma-cash-tx.ts
* Deprecated function in favor of UnmarshallPB
* Added console.warn in order to warn about the deprecated function
=> Deprecated function UmarshallPB

src/contracts/dpos2.ts, src/dpos/dpos-user.ts, src/proto/dposv2.proto, src/proto/dposv2_pb.d.ts
Adds function to query Time until next election for DPoS
=> Add Time until Election bindings

src/contracts/dpos2.ts
Adjustments for https://github.com/loomnetwork/loomchain/pull/727
=> Update DPOS2.delegateAsync to call new version of Delegate method on DPOSv2 contract

src/contracts/dpos2.ts, src/dpos/dpos-user.ts
Add bindings for redelegation, after popular demand
=> add redelegate bindings

src/contracts/dpos2.ts, src/dpos/dpos-user.ts, src/proto/dposv2.proto, src/proto/dposv2_pb.d.ts
Match https://github.com/loomnetwork/go-loom/compare/list-delegators
=> List Delegations bindings

src/contracts/dpos2.ts, src/dpos/dpos-user.ts, src/proto/dposv2.proto, src/proto/dposv2_pb.d.ts
Bindings to go with https://github.com/loomnetwork/loomchain/pull/762.
=> Check all delegations bindings

package.json, scripts/fix_types.sh, yarn.lock
SSHPK update for fix https://nvd.nist.gov/vuln/detail/CVE-2018-3737
=> Update script and yarn lock

src/contracts/transfer-gateway.ts, src/dpos-user.ts, src/proto/transfer_gateway.proto, src/proto/transfer_gateway_pb.d.ts
Simple method to call on dposUser to check if user has any tokens that haven't been credited to them in the dappchain. If the amount is >0, the UI shoudl enable the button that calls `reclaimDepositorTokensAsync`
=> Get reclaimable tokens bindings

src/contracts/dpos2.ts, src/dpos-user.ts, src/proto/dposv2.proto, src/proto/dposv2_pb.d.ts
add optional parameter when checking a distribution, goes with https://github.com/loomnetwork/loomchain/pull/895
=> Check distribution param

src/contracts/dpos3.ts, src/proto/dposv3.proto, src/proto/dposv3_pb.d.ts
Match https://github.com/loomnetwork/go-loom/pull/370/files changes.
=> Validator statistic

src/contracts/dpos3.ts, src/dpos-user-v3.ts, src/proto/dposv3.proto, src/proto/dposv3_pb.d.ts
Depends on:
- https://github.com/loomnetwork/loomchain/pull/1128/files
- https://github.com/loomnetwork/go-loom/pull/380
=> Protos and client modifications for improving UX on checking/claiming rewards

src/contracts/user-deployer-whitelist.ts
Issue: https://github.com/loomnetwork/loom-js/issues/271
=>  UserDeployerWhitelist#271 added unmarshal the responses with IDeployer

src/contracts/user-deployer-whitelist.ts, src/proto/user_deployer_whitelist.proto, src/proto/user_deployer_whitelist_pb.d.ts
1)Changes in proto definitions
2)Corresponding Support for contract methods added.
=> Get/Modify Tier Info support - User-Deployer-Whitelist

src/address.ts
=> Fix LocalAddress equals, UnmarshalPB functiom

src/loom-provider.ts
- Small refactoring on eth subscription structure
=> Added back the reset function

.travis_e2e_test.sh, src/loom-provider.ts, src/tests/e2e/loom-provider-web3-tests.ts
=> Adding get storage at tests

src/contracts/transfer-gateway.ts, src/proto/transfer_gateway.proto, src/proto/transfer_gateway_pb.d.ts
=> Add TransferGateway.getContractMappingAsync

src/contracts/transfer-gateway.ts, src/proto/transfer_gateway.proto, src/proto/transfer_gateway_pb.d.ts
=> Add TransferGateway.getLocalAccountInfoAsync

src/contracts/dpos3.ts
A candidate that was just registered without being whitelist first will not have a statistic until after the first post-registration election.
So `getCandidatesAsync()` should not assume every candidate has stats!
=> Make DPOS3.getCandidatesAsync() handle candidates with missing stats
