loomnetwork/loom-js

package.json, src/address.ts, src/client.ts, src/contract.ts, src/evm-contract.ts, src/index.ts, src/internal/ws-rpc-client.ts, src/tests/address_test.ts, src/tests/integration_test.ts
`Client` and `Contract` are now both event emitters, so they have acquired
the [Node EventEmitter API](https://nodejs.org/api/events.html).
```typescript
// listen to events emitted by a specific smart contract
contract.on/once(Contract.EVENT, (event: IChainEventArgs) => {
// handle event
})
// listen to events emitted by any smart contract
client.on/once(ClientEvent.Contract, (event: IChainEventArgs) => {
// handle event
})
```
TODO:
=> Add ability to subscribe to contract events via WebSocket

src/client.ts, src/internal/ws-rpc-client.ts, src/proto/loom.proto, src/proto/loom_pb.d.ts
Topics aren't currently exposed via the client API, and the client will receive all events from the chain. EventData is now a protobuf, but it turns out the js protobuf lib doesn't have any built-in functionality
to decode a JSON-encoded protobuf.
=> Update client event subscription to work with new loomchain

src/client.ts, src/helpers.ts, src/index.ts, src/tests/e2e/contract-tests.ts, src/tests/e2e/evm-contract-tests.ts
Right now the intended use case is just to use multiple key pairs to send txs with a single client.
=> Add ability to override the set of middleware used on a per tx basis

src/loom-provider.ts
* LoomProvider now is able to manage accounts private/public keys
* Constructor now requires a private key for the main account
* LoomProvider signs transactions using the new account management
Example of how LoomProvider will work
---
```Typescript
/**
* Constructs a new TruffleLoomProvider using LoomProvider to provide connection to Loom DAppChain.
* @param chainId DAppChain identifier.
* @param writeUrl Host & port to send txs, specified as "<protocol>://<host>:<port>".
* @param readUrl Host & port of the DAppChain read/query interface, this should only be provided
*                if it's not the same as `writeUrl`.
* @param privateKey Account private key in Base64 string format
*/
constructor(chainId: string, writeUrl: string, readUrl: string, privateKey: string) {
const _privateKey …
```
=> LoomProvider managing accounts

src/loom-provider.ts
Solidity default state for variables not defined is `0x0`, so to avoid errors of empty `Buffer` on `LoomProvider` and be friendly to `web3js` the return instead of `undefined` is `0x0`. Also it will fix the behavior of the command `truffle migrate` when the migrations doesn't exists on `DappChain`
=> Fix default return for eth_call

src/plasma-cash/solidity-helpers.ts
Ganache and MetaMask appear to implement web3.eth.sign differently:
- Ganache sets v to 1, while MetaMask sets it to 28
- Ganache prefixes the msg before signing, MetaMask doesn't
So we do our best to guess what actually happened and set the sig mode accordingly so the Address Mapper contract knows how to recover the signer address from the sig.
=> Set correct sig mode when signing a message via MetaMask

src/address.ts
Useful when you need to pass a DAppChain address to web3.
=> Add LocalAddress.toChecksumString()

e2e_tests.sh, src/contract.ts, src/plasma-cash/dappchain-client.ts, src/plasma-cash/entity.ts, src/plasma-cash/ethereum-client.ts, src/proto/plasma_cash.proto, src/proto/plasma_cash_pb.d.ts, src/tests/e2e/client-evm-tests.ts, src/tests/e2e/loom-provider-eth-filters-2.ts
Adds two methods:
- `getPlasmaTx`: This calls the `GetPlasmaTx` method of Loomchain and returns the transaction at a slot at a specific block. This is required for the exclusion proofs during history verification of a coin.
- `getUserCoins`: This calls the `GetUsersSlots` method of Loomchain to retrieve all the slots (coinIds) that the user owns. Subsequently it calls `getPlasmaCoinAsync` on each of them in order to retrieve relevant metadata. 
With these functions the Plasma Cash API is complete and a full client can be built.
=> Coin History Verification & Get all user slots

src/plasma-cash/db.ts
* This fix help to avoid the error
https://github.com/typicode/lowdb/issues/211 which happens when webpack
loader import the module graceful-fs calling a fs module from Node.js
which isn't available on webpack, by lazy loading the loom-js only calls
when necessary (only when used on Node.js)
=> Lazy loading lowdb/adapters

src/contracts/address-mapper.ts, src/index.ts, src/solidity-helpers.ts
AddressMapper.addIdentityMappingAsync() now accepts IEthereumSigner instead of Web3Signer, the interface is implemented by both Web3Signer and OfflineWeb3Signer. The former should be used in the browser, and latter in NodeJS.
=> Export OfflineWeb3Signer

src/plasma-cash/entity.ts, src/plasma-cash/user.ts
- Add `receiveCoin` function. This should be called by a user when refreshing their coin state. On the user side, after receiving the coin and validating the output is true, they should start watching.
- FIx certain 'optimizations' which didn't save user state correctly.
=> Bug fixes in block search for exits/transfers

.travis_e2e_test.sh, e2e_plasma_cash_test.sh, e2e_support/plasma-cash/honest.genesis.json, e2e_support/plasma-cash/hostile.genesis.json, src/index.ts, src/plasma-cash/user.ts, src/solidity-helpers.ts, src/tests/e2e/address-mapper-tests.ts, src/tests/e2e/plasma-cash/challenge-after-demo.ts, src/tests/e2e/plasma-cash/challenge-before-demo.ts, src/tests/e2e/plasma-cash/challenge-between-demo.ts, src/tests/e2e/plasma-cash/complex-demo.ts, src/tests/e2e/plasma-cash/config.ts, src/tests/e2e/plasma-cash/demo.ts, src/tests/e2e/plasma-cash/respond-challenge-before-demo.ts
- Adds `setupAccounts`, `disconnectAccounts` methods for easier testing with multiple accounts
- Register eth/dappchain keypair to the address mapper during creation if it does not exist
- createUser takes a `dappchainPrivateKey` argument. For `createMetamaskUser` this should be modified to be the private key taken from the `localstorage`. If a user is not registered in the address mapper, they'll be prompted by Metamask to sign a message to register them
This adds some extra burden for users because they need to manage 2 keys, but it's a requirement for security.
=> Add AddressMapper Auth

src/plasma-cash/user.ts
The previous implementation was returning `undefined`  for `defaultAccount`
=> Fixed issue to get default wallet address

.travis_e2e_test.sh, src/plasma-cash/entity.ts, src/tests/e2e/plasma-cash/challenge-between-demo.ts
Closes https://github.com/loomnetwork/loom-js/issues/156, now checks that the previous block of a transaction is the last included block. This makes users reject coins that have double spends in their history
=> Coin history fix

src/loom-provider.ts
* Loom was responding getevmblockbynumber with EvmTxReceipt, and now is
returning the right type EvmTxObject
=> Fix transaction result on `getevmblockbynumber`

src/client.ts
The error message is now more verbose in recent loom builds.
=> Fix nonce mismatch error detection

.travis_e2e_test.sh, e2e_tests.sh, src/client.ts, src/tests/e2e/loom-provider-eth-get-logs.ts
The client now sends txs to the `broadcast_tx_sync` endpoint by default and then polls the node for the result (assuming the tx passed CheckTx).
Probably need to tweak the retry options that control the polling behavior.
=> Poll for tx results instead of waiting for the node to commit tx

.travis_e2e_test.sh, src/middleware/cached-nonce-tx-middleware.ts, src/plasma-cash/user.ts, src/tests/e2e/client-test-tx-cache.ts
The cached nonce in `CachedNonceTxMiddleware` was previously incremented regardless of whether or not the tx was valid and/or successful, this caused the tx after a failed tx to fail even when it should've succeeded. The cached nonce is now only incremented once it is known that the last tx that was sent is valid, though whether or not a tx was actually successful is only known when using the `TxCommitBroadcaster` (which is no longer the default broadcaster).
The cached nonce is also re-synced with the node whenever a tx fails (though that may need to be tweaked some more to handle TM errors).
=> Fix CachedNonceTxMiddleware to increment nonce only for valid/successful txs

.travis_e2e_test.sh, e2e_plasma_cash_test.sh, e2e_tests.sh, src/client.ts
This makes it possible to create a single client that sends txs to a validator node, and sends all other queries to a non-validator node.
=> Query nonce from write URL instead of read URL 

.travis.yml, src/client.ts, src/dpos/dpos-user.ts, src/helpers.ts, src/plasma-cash/user.ts, src/tests/unit/client-url-override-tests.ts, src/tests/unit_tests.ts
Only doing this for the most common code path, override can still be
bypassed if needed.
=> Override read URL for PlasmaChain production cluster

src/contracts/transfer-gateway.ts
Only the Gateway owner can specify a list of depositor accounts, regular
users can just reclaim tokens for their own account.
=> Make TransferGateway.reclaimDepositorTokensAsync depositor list optional

scripts/abi.js
`ts_generator.tsGenerator` is an async function.
=> Fix contract typings generation script

src/loom-provider.ts, src/tests/e2e/loom-provider-tests.ts, src/tests/e2e/loom-provider-web3-tests.ts
`eth_blockNumber` is supposed to return the block number in base 16, prefixed by `0x` as per https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_blocknumber - while LoomProvider was returning it as a base 10 number.
=> Tweak test for eth_blockNumber to verify the block number is hex encoded

src/loom-provider.ts
Otherwise static calls to EVM contracts may end up with the wrong caller chain ID & address.
=> Make LoomProvider respect caller chain ID override for static calls

src/contracts/loomcoin-gateway.ts
Should read "ethereum LOOM contract address" instead of "ethereum gateway address"
=> Fix LoomCoinTransferGateway.withdrawLoomCoinAsync argument doc

README.md
Removes eth_estimateGas from the list of supported JSON RPC calls
=> Removes eth_estimateGas from the list of supported JSON RPC calls

src/contracts/transfer-gateway.ts, src/ethereum-gateways.ts
This fixes `TransferGateway.withdrawalReceiptAsync()` to only unmarshal
the token contract address when it's available. When withdrawing LOOM
via the Binance Gateway the token contract address is not set on the
withdrawal receipt.
=> Don't unmarshal TokenContract address on receipt if it's missing

src/contracts/binance-gateway.ts
It shouldn't be necessary to specify the token contract in the request, but validation checks in the gateway contract (activated by `tg:v1.2` feature flag) will fail if it's missing, so until the contract is fixed up we need to specify some kind of address (though only the chain ID matters).
=> Specify token contract when withdrawing LOOM to Binance Chain

package.json, scripts/export-mainnet-contracts-abi.js, src/ethereum-gateways.ts
The typings generated by TypeChain for the Gateway Solidity contracts weren't copied to the dist directory and therefore weren't published in the NPM package, this caused compile errors (TS2307) in projects that imported loom-js.
```
node_modules/loom-js/dist/dpos-user.d.ts:7:64 - error TS2307: Cannot find module './mainnet-contracts/EthereumGatewayV2'.
node_modules/loom-js/dist/ethereum-gateways.d.ts:38:14 - error TS2416: Property 'version' in type 'EthereumGatewayV1' is not assignable to the same property in base type 'IEthereumGateway'.
Type 'number' is not assignable to type 'GatewayVersion'.
```
=> Fix a couple of issues causing errors TS2307 & TS2416
